### ISSUE TITLE
missing implementation for routine is_valid_account_number from class ACCOUNT_NUMBER

### ISSUE THREAD

**Issue by nicodomgz** [nmaguirre/eiffel-bank-ocr#12]
Implementation for Method ACCOUNT.NUMBER.is_valid_account_number is missing.

**Comment by nicodomgz** [comment]
Solved in rev. 19a3a58

**Comment by ibongiovanni** [comment]
There's missing a sentence that increases the value of i inside the loop

**Comment by nmaguirre** [comment]
The last if-then-else and the assignment to the Result variable can be simplified. Instead of checking the condition, assigning the value to a local variable, and then assigning the value of this variable to Result, you can directly assign the evaluation of the condition to Result. Please resolve this problem. I'm removing the 'resolved' tag for the moment. Thanks!

**Comment by nmaguirre** [comment]
Please bare in mind ibongiovanni's comment. Your loop is an infinite loop, you never increment variable i. Please solve asap. Thanks!

**Comment by nicodomgz** [comment]
Solved in rev b47f11e

**Comment by nmaguirre** [comment]
The implementation of the routine is wrong. Please follow the guidelines provided in http://codingdojo.org/cgi-bin/index.pl?KataBankOCR

Your checksum is not the one that should be implemented. I'm removing the 'resolved' tag.

**Comment by nicodomgz** [comment]
Solved in rev  48060c2

**Comment by nmaguirre** [comment]
I don't see it. It still implements something different from what http://codingdojo.org/cgi-bin/index.pl?KataBankOCR states as the checksum (which by the way is a lot simpler to compute). I'm removing the resolved tag. Notice that some tests evaluating this routine are not passing.

**Comment by nicodomgz** [comment]
Resolved in rev  5d6dac5

**Comment by nricci** [comment]
The code appear sot be correct and the test is passing now. I'm closing the issue.

**Comment by ezedepetris** [comment]
other guy resolved the problem
