### ISSUE TITLE
missing precondition for routine set_digit from class ACCOUNT_NUMER

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/eiffel-bank-ocr#16]
precondition for ACCOUNT_NUMBER.set_digit is missing

**Comment by gamassimino** [comment]
solved in rev. 5fdb707

**Comment by dahue** [comment]
@gamassimino there is a bug with the precondition, right now is: "valid_position: (pos>=0 and pos<9)" and should be: valid_position: (pos>=1 and pos<10)

**Comment by gamassimino** [comment]
Sorry, solved in rev. d7eb710
