### ISSUE TITLE
Missing implementation for routine set_account_number_from_string_rep from class ACCOUNT_NUMBER

### ISSUE THREAD

**Issue by andruvetto** [nmaguirre/eiffel-bank-ocr#18]
implementation for routine set_account_number_from_string_rep from class ACCOUNT_NUMBER is missing

**Comment by andruvetto** [comment]
Solved in ea1bd5c

**Comment by dromero19** [comment]
Sorry, but the implementation of this routine is incorrect. You have to set 'value' somehow with the given parameter 'new_value'. You don't need the local variables declared. If you want I resolve this issue. Correct me if I'm wrong.

**Comment by dromero19** [comment]
Sorry, my last comment is for another issue.

**Comment by nmaguirre** [comment]
Seems to be alright! Well done!
