### ISSUE TITLE
Missing precondition for routine ACCOUNT_DIGIT.make_from_string_rep 

### ISSUE THREAD

**Issue by ibongiovanni** [nmaguirre/eiffel-bank-ocr#19]
precondition for  ACCOUNT_DIGIT.make_from_string_rep  is missing

**Comment by ibongiovanni** [comment]
Resolved in rev c742e0d

**Comment by nmaguirre** [comment]
Well done! Thanks!

**Comment by ezedepetris** [comment]
sorry i make a mistake and delete that precondition, i resolved the problem and rewrite the precondition and remplace with a preondition more strong in the rev e9f89a6, sorry about that!
