### ISSUE TITLE
Missing  comments for ACCOUNT_DIGIT.set_value

### ISSUE THREAD

**Issue by jicibils** [nmaguirre/eiffel-bank-ocr#2]
Comments set_value from class ACCOUNT_DIGIT is not implement. Implement this routine following the conventions, syntactic and methodological rules of Eiffel.

**Comment by jicibils** [comment]
Resolved in rev.: 4dc90fe

**Comment by jicibils** [comment]
Resolved in rev.: 96acec2

**Comment by nmaguirre** [comment]
I'm removing the "resolved" tag from this issue. Comments do not follow Eiffel's convention. Routine's description should follow its signature. For example:

set_value(new_value: INTEGER)
-- Changes the value of the account digit
do
...
end

Also, the comment inside the body of the routine is unnecessary. Please remove it and correct the comment.

**Comment by jicibils** [comment]
Resolved in rev.: 374bd32

**Comment by nmaguirre** [comment]
Well done! Comment should be appropriately indented, but it's alright for the moment. Thanks!
