### ISSUE TITLE
missing implementation for routine make_from_string_rep from class ACCOUNT_DIGIT

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/eiffel-bank-ocr#20]
missing impletation for routine make_from_string_rep form class ACCOUNT_DIGIT

**Comment by ezedepetris** [comment]
Resolved in rev 5a3ebf3

**Comment by andruvetto** [comment]
Sorry, but the implementation of this routine is incorrect. Always assigns the value 9

**Comment by ezedepetris** [comment]
Resolved in rev ac71471
