### ISSUE TITLE
Missing test for routine set_value_from_string_rep in class ACCOUNT_DIGIT

### ISSUE THREAD

**Issue by nricci** [nmaguirre/eiffel-bank-ocr#21]
Provide appropriate test/s for the routine set_value_from_string_rep in class ACCOUNT_DIGIT.

**Comment by vikibueno** [comment]
Solved in rev. a144f5d

**Comment by rdegiovanni** [comment]
This "|_|  |  |" is not the correct representation of the number four when you create the account digit.
Please correct your test as soon as possible.

**Comment by jicibils** [comment]
Resolved in rev. 394722c
