### ISSUE TITLE
Missing implementation for routine ACCOUNT_NUMBER.make

### ISSUE THREAD

**Issue by lukax77** [nmaguirre/eiffel-bank-ocr#22]
Implementation for routine make from class ACCOUNT_NUMBER is missing.

**Comment by lukax77** [comment]
Resolved in rev. 9c5fb8c

**Comment by nmaguirre** [comment]
You got the rev. number wrong, apparently. Anyway, your implementation uses an obsolete routine (please have a look at the warning that Eiffel Studio produces). Please check the warning, and use a non-obsolete constructor for the array. I'm removing the "resolved" tag for the moment. Thanks!

**Comment by lukax77** [comment]
The revision number is wrong, sorry for that.
I see no warning when I compile the code (My version of EiffelStudio is 15).
I only found the following constructors methods:
make_empty, make, make_filled, make_from_array, make_from_special, make_from_cil,
which one should I use, or are there others that I can't find in the documentation of Eiffel

**Comment by lukax77** [comment]
I changed the constructor method for make_filled.
Resolver rev. b7db203
