### ISSUE TITLE
 Missing comment for routine ACCOUNT_NUMBER. set_account_number

### ISSUE THREAD

**Issue by vikibueno** [nmaguirre/eiffel-bank-ocr#23]
Comments set_account_number from class ACCOUNT_NUMBER is not implement. Implement this routine following the conventions, syntactic and methodological rules of Eiffel.

**Comment by gamassimino** [comment]
solved in rev. 5812eae

**Comment by vikibueno** [comment]
solved in rev. bd72a1a
