### ISSUE TITLE
Missing test for routine set_account_number_from_string_rep in class ACCOUNT_NUMBER

### ISSUE THREAD

**Issue by nricci** [nmaguirre/eiffel-bank-ocr#24]
Provide appropriate test/s for the routine.

**Comment by ibongiovanni** [comment]
Implemented in rev c97edd5

**Comment by nmaguirre** [comment]
It seems alright. We have to come up with a convention for out, though. Will out represent the account number as a string of digits, or as a string of pipes, underscores and blanks? It seems you assumed the first choice!

I'm closing the issue for the moment. We'll see later on if it needs to be updated.

Well done!

**Comment by rdegiovanni** [comment]
Your tests doesn't provide the correct codification of number 4 in the string that you use to call routine set_account_number_from_string_rep of class ACCOUNT_NUMBER.
Please correct your test as soon as possible, and use it to debug the corresponding routine you are testing.

**Comment by ibongiovanni** [comment]
Resolved in rev c62a40d
