### ISSUE TITLE
Missing test for routine set_digit in class ACCOUNT_NUMBER

### ISSUE THREAD

**Issue by nricci** [nmaguirre/eiffel-bank-ocr#26]
Provide appropriate test/s for the routine.

**Comment by dahue** [comment]
Solved in 24ea29b

**Comment by dahue** [comment]
There is a bug with the lines:
account_number.set_digit (0, account_digit)
assert ("Should have a 5 in position 0", account_number.number[0].value = 5)
position=0 is not valid. Should be another value between 1 and 9, say:
account_number.set_digit (1, account_digit)
assert ("Should have a 5 in position 1", account_number.number[1].value = 5)

**Comment by dahue** [comment]
Bug solved in e566f28
