### ISSUE TITLE
Missing Implementation for routine ACCOUNT_NUMBER.out 

### ISSUE THREAD

**Issue by guttlein** [nmaguirre/eiffel-bank-ocr#30]
Implementation for routine ACCOUNT_NUMBER.out is missing. I'm gonna do it following the conventions and syntactics of Eiffel.

**Comment by guttlein** [comment]
Implementation for Out is Done! Waiting for job!
Solved in: b0d1032cf12c1267adc13d6eb0cefeeea41e59d1

**Comment by nmaguirre** [comment]
Please use English for the code. For instance, instead of "linea" as the name of a variable, you should use "line", or "row". It will make it easier to go through the code for debugging or extending functionality, for other developers. I'm removing the "resolved" tag for the moment. Thanks!

**Comment by guttlein** [comment]
Done!

**Comment by nmaguirre** [comment]
Please use the following conventions:
- all lower case for variables
- first letter in capital, the rest in lower case, for constants
- all letters in capital, for class names.
  I'm removing the 'resolved' tag for the moment. Thanks!

**Comment by nmaguirre** [comment]
There's another problem. Local variable 'printer' is never initialised, leading to a call on void target exception. Please solve this problem too. Thanks!

**Comment by nicoboccolini** [comment]
solved in rev. 4d93c624a0acb35b6d1c96c1fb92fef62001f856

**Comment by nmaguirre** [comment]
Well done! Thanks!
