### ISSUE TITLE
Missing precondition for routine ACCOUNT_NUMBER.set_account_number

### ISSUE THREAD

**Issue by dromero19** [nmaguirre/eiffel-bank-ocr#37]

**Comment by dromero19** [comment]
Solved by @marianoruano. Rev. not reported

**Comment by nmaguirre** [comment]
First part of the 'require' clause is redundant. Please remove! Thanks!

**Comment by marianoruano** [comment]
Precondition fixed. Solved in rev. a5ca735

**Comment by nmaguirre** [comment]
It seems you got the rev. number wrong.

The first part of the precondition is redundant. Since other_account_number is an INTEGER, an expanded type, it will certainly be non-Void. Please remove that part of the precondition.

I'm removing the 'resolved' tag for the moment.

**Comment by marianoruano** [comment]
Precondition fixed. Solved in rev. e640fc6.

**Comment by nricci** [comment]
Seem alright. Would it be reasonable to enforce is_valid_account_number as precondtion?

**Comment by marianoruano** [comment]
Is not possible to use that routine because don't take parameters . Also this routine don't verify an integer number but also check if the array number is correct.
