### ISSUE TITLE
Missing test for routine ACCOUNT_NUMBER.set_account_number 

### ISSUE THREAD

**Issue by mromina** [nmaguirre/eiffel-bank-ocr#38]

**Comment by dromero19** [comment]
Solved in rev. 75b6fc6 by @dastorga

**Comment by nmaguirre** [comment]
Please notice that routine get_set_account_number is wrong. Feature number should be used instead. Please correct your tests and remove this erroneous routine. I'm removing the resolved tag.

**Comment by dromero19** [comment]
Final version in rev. a0cdf0f. Solved by @dastorga
