### ISSUE TITLE
Missing postcondition for routine set_account_number from class ACCOUNT_NUMBER

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/eiffel-bank-ocr#39]

**Comment by gamassimino** [comment]
Solved in rev. c024b9f

**Comment by nmaguirre** [comment]
Please notice that the postcondition is wrong. You are comparing an array of account digits with an integer number. Please correct. I'm removing the resolved tag.

**Comment by gamassimino** [comment]
you right, but I don't know how to say that the array now has other_account_number
the postcondition always are expresions?

**Comment by nmaguirre** [comment]
You may add a routine that produces an integer representation from the array of account digits, say, as_integer. Then you can compare the "set" received parameter with the number.as_integer.

Thanks!

**Comment by gamassimino** [comment]
solved in rev. 7e38ef8

**Comment by gamassimino** [comment]
sorry but the implementation for routine as_values is wrong

**Comment by gamassimino** [comment]
solved in rev. 95a16a7

**Comment by nmaguirre** [comment]
Well done! Thanks!
