### ISSUE TITLE
missing comment for ACCOUNT_DIGIT.invariant

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/eiffel-bank-ocr#4]
comments invariant is not implemented

**Comment by ezedepetris** [comment]
resolved in rev. bcf6e513cbc28bf832cab5bec1a268adc87507c9

**Comment by nmaguirre** [comment]
Please be more direct in the invariant definition:

invariant
    -- value must be a digit, i.e., a value between 0 and 9
...

Also, the invariant should have a tag (a representative name at the beginning). For instance:

value_is_digit: ...

Please correct this issue. I'm removing the resolved tag. Thanks!
