### ISSUE TITLE
Missing precondition for routine is_valid_account_number from class ACCOUNT_NUMBER

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/eiffel-bank-ocr#40]

**Comment by gamassimino** [comment]
solved in rev. ba9eef0

**Comment by nmaguirre** [comment]
The precondition is actually always True, in this case. Notice that as_integer, returning an attached integer value, will never be Void. It may perfectly be the case that the precondition for this routine is indeed true, but it should be more clearly stated. If you agree with me in this, please change the implementation, removing altogether the precondition. I'm removing the 'resolved' tag. Thanks!

**Comment by gamassimino** [comment]
solved in rev. 934ceae

**Comment by nmaguirre** [comment]
I still think this routine's precondition is indeed True. In my opinion, the precondition should be removed altogether. The idea is that the precondition states which special states are the only allowed states in which the routine is allowed to be called. What you put in the precondition is simply something that should always hold, not a precondition for this routine. Please remove the precondition altogether. Thanks!

**Comment by gamassimino** [comment]
sorry but this routine don't has precondition, I may have made a mistake when i did the "push"
maybe the number of the commit is wrong

**Comment by nmaguirre** [comment]
You are right. Issue solved. I'm closing it. Cheers! Well done!
