### ISSUE TITLE
Description missing classes account_number and account_digit

### ISSUE THREAD

**Issue by dastorga** [nmaguirre/eiffel-bank-ocr#41]

**Comment by gamassimino** [comment]
solved in rev. 8e36b5a

**Comment by nmaguirre** [comment]
Please be more precise on what routine your issue applies to. That is, issues for comments, implementations, contracts or tests must be defined in a per feature fashion. Thanks!

**Comment by dastorga** [comment]
Sorry, the issue is for class description
