### ISSUE TITLE
Missing precondition for set_account_number_from_string_rep from class ACCOUNT_NUMBER

### ISSUE THREAD

**Issue by castagneris** [nmaguirre/eiffel-bank-ocr#42]

**Comment by castagneris** [comment]
Solved in rev. 8e784a1

**Comment by nmaguirre** [comment]
Sorry, but the routine does not have a precondition, at least it doesn't in the main repo. Did you push your local changes? Please check if you have your changes locally, commit and push. I'm removing the 'resolved' tag.

**Comment by castagneris** [comment]
Sorry, solved in rev, 5efdd9e

**Comment by nmaguirre** [comment]
Well done! Thanks!
