### ISSUE TITLE
Missing unit tests for routine out from class ACCOUNT_NUMBER

### ISSUE THREAD

**Issue by damarisg** [nmaguirre/eiffel-bank-ocr#43]
There are no unit tests checking the functionality of routine out from class ACCOUNT_NUMBER. At least one test that checks the behaviour of this routine must be provided.

**Comment by damarisg** [comment]
Solved in rev. c224696

**Comment by nmaguirre** [comment]
Please do not use '=' for comparison. Use 'is_equal' instead. I'm removing the 'resolved' tag. Thanks!

**Comment by damarisg** [comment]
Solver in rev. e8562c0

**Comment by nmaguirre** [comment]
Well done! Thanks!

**Comment by nicoboccolini** [comment]
This test is not correct! it return  

  | _  _ |_| _  _  _  _  _ 
  |   _| _|  ||_ |_   ||_||_|
  ||_  _|  | _||_|  ||_|  |

**Comment by nicoboccolini** [comment]
solver in rev. 1a9d3c31f2d0f7ee2e2e42840aaf46669c84089e

**Comment by nmaguirre** [comment]
Well done! Thanks!
