### ISSUE TITLE
Missing precondition in routine ACCOUNT_DIGIT.make_from_string_rep

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/eiffel-bank-ocr#44]

**Comment by ezedepetris** [comment]
Resolved in rev e9f89a6

**Comment by nmaguirre** [comment]
Precondition has been successfully added, and as far as I can tell it's correct (it even has a label, great!). But the rev. number is not for this change. I'm closing this issue. Thanks! Great job!
