### ISSUE TITLE
Missing Implementation for routine ACCOUNT_DIGIT.is_a_valid_string_rep

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/eiffel-bank-ocr#45]
this routine should controls if the stringis a valid string for represent a dígito of a ACCOUNT_DIGIT

**Comment by ezedepetris** [comment]
Resolved in rev e6d606b

**Comment by nmaguirre** [comment]
What's the meaning of first_part, second_part, third_part? I think the names of the variables do not represent a meaningful condition. Even though it may be a longer implementation, why not have as many boolean variables as possible digits? I mean, is_zero, is_one, etc? It will also be easier to debug. Please change the implementation. I'm removing the 'resolved' tag. Thanks!

**Comment by ezedepetris** [comment]
yes, sorry about that, you have right, i repar on the next Rev a1b17bf the first_part, second_part and third part was only to make shorter the condition but I understood that it was ambiguous.
thanks!

**Comment by nmaguirre** [comment]
Well done! Thanks!
