### ISSUE TITLE
missing implementation for routine make from class ACCOUNT_DIGIT

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/eiffel-bank-ocr#5]
Routine make from class ACCOUNT_DIGIT is not implemented. Implement this routine following the conventions, syntactic and methodological rules of Eiffel.

**Comment by gamassimino** [comment]
resolved in rev. 4dc90fe

**Comment by nmaguirre** [comment]
Well done! I'm closing this issue. Thanks!
