### ISSUE TITLE
Missing test for routine ACCOUNT_DIGIT.set_value

### ISSUE THREAD

**Issue by mromina** [nmaguirre/eiffel-bank-ocr#51]

**Comment by mromina** [comment]
Solved in rev. e19459d

**Comment by ibongiovanni** [comment]
Sorry, but it's missing the statement that creates the object ACCOUNT_DIGIT

**Comment by arangue** [comment]
Solved in rev. d4b914d

**Comment by mromina** [comment]
Yes, it's true, sorry. I notice that this test is already implemented with the name: 'test_account_digit_set_get'. I suggest change the name test with another name more representative. I will eliminate my implementation of this test.

**Comment by mromina** [comment]
Elimination of repeated test in class test_account_digit. Rev a41d35f
