### ISSUE TITLE
Missing comment for routine is_a_valid_string_rep from class ACCOUNT_DIGIT

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-bank-ocr#53]
Missing comment for routine is_a_valid_string_rep from class ACCOUNT_DIGIT. An appropriate comment, briefly describing the routine's behaviour, must be added. Please follow Eiffel's conventions (see other routine descriptions in the class).

**Comment by lukax77** [comment]
Resolver rev. c9475e4

**Comment by nmaguirre** [comment]
Well done!
