### ISSUE TITLE
Missing comment for routine out from class ACCOUNT_NUMBER_TESTS

### ISSUE THREAD

**Issue by damarisg** [nmaguirre/eiffel-bank-ocr#54]
Comment for routine out from class ACCOUNT_NUMBER_TEST is missing.

**Comment by damarisg** [comment]
Solved in rev. 4b4567f

**Comment by nmaguirre** [comment]
I would put something different, such as:

"tests that the out routine, producing a textual representation of the account number using pipes, underscores and blanks, works correctly."

Please make the comment clearer. Thanks!

**Comment by damarisg** [comment]
Solved in rev. 79e0a7d

**Comment by nmaguirre** [comment]
Well done!
