### ISSUE TITLE
Missing tests for routine  ACCOUNT_DIGIT.out

### ISSUE THREAD

**Issue by mromina** [nmaguirre/eiffel-bank-ocr#55]

**Comment by mromina** [comment]
Solved in rev.d056a73

**Comment by mromina** [comment]
Solved in rev. d056a73

**Comment by nmaguirre** [comment]
Please don't use '=' to compare strings (it's wrong). Use routine is_equal instead (e.g., str.is_equal(d.out)). Thanks!

**Comment by nmaguirre** [comment]
Don't forget to tag your issue with 'resolved' when you are done.

**Comment by mromina** [comment]
Test fixed. Solved in rev. 9009776

**Comment by nmaguirre** [comment]
Please notice that "one" is just two pipes, not three. Please correct your test. Thanks! I'm removing the 'resolved' tag.

**Comment by mromina** [comment]
Solved in rev. fcf6b68

**Comment by mromina** [comment]
Minor change in test. Solved in rev. 3ec43c1
