### ISSUE TITLE
Missing implementation for APPLICATION.make, the main routine

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-bank-ocr#56]
The implementation of the main routine is missing. This routine is make from class APPLICATION. It contains some code showing how some lines can be read from a text file (it actually reads the first "account number" from a text file, and according to it being valid or not, it prints out the account number plus OK, or ERR, respectively. 

The actual behaviour of this routine must be: read ALL account numbers in the file, output them as normal characters, appending OK or ERR according to whether the account is valid or not. The name of the file holding the account numbers should be provided from the command line.

**Comment by ezedepetris** [comment]
Resolved in rev b7093ea and a3d7a2c, obviusly that it allows a lot of interpretation i did a sample interpretation of how to read an account number of a file, and it allows other implementations more strongest and efficient,

**Comment by nricci** [comment]
The main routine is not working properly. When I run it on the accounts.txt file provided, I get the following exception trace:

---

## Class / Object      Routine                Nature of exception           Effect

ACCOUNT_NUMBER      set_account_number_from_string_rep @2

## <000000010E24ADE8>                         Precondition violated.        Fail

ACCOUNT_NUMBER      make_from_string @9                                 

## <000000010E24ADE8>                         Routine failure.              Fail

APPLICATION         make @16                                            

## <000000010E24A5A8>                         Routine failure.              Fail

APPLICATION         root's creation                                     

## <000000010E24A5A8>                         Routine failure.              Exit

**Comment by ezedepetris** [comment]
Resolved in rev 3993da6

**Comment by nmaguirre** [comment]
It's working! The body of the main loop is not "structured", but it works. Well done! Thanks!
