### ISSUE TITLE
Missing definition of const for string representation for numbers in class ACCOUNT_DIGIT

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/eiffel-bank-ocr#58]

**Comment by gamassimino** [comment]
solved in rev. cd2bbfb

**Comment by ibongiovanni** [comment]
Representation of 4 is not "`|_|  |`"? instead of "`|_|  |  |`".

**Comment by gamassimino** [comment]
you right, it's copy and paste i'm sorry
solved in rev. a6538d9

**Comment by ibongiovanni** [comment]
It´s ok, I think 1 and 4 were the only  misunderstandings

**Comment by gamassimino** [comment]
changed rep_nine in rev. f5a71e5
