### ISSUE TITLE
missing comment for routine ACCOUNT_DIGIT.set_value_from_string_rep

### ISSUE THREAD

**Issue by lukax77** [nmaguirre/eiffel-bank-ocr#6]
Missing comment for routine ACCOUNT_DIGIT.set_value_from_string_rep.

**Comment by lukax77** [comment]
resolved in rev. ad00fc2

**Comment by nmaguirre** [comment]
Comment does not follow Eiffel's conventions. Comments should be immediately after the routine's name, e.g.:

routine (routine_param: T)
         -- Creates ....
    do
        ....
    end

Please correct this comment. I'm removing the "resolved" tag. Thanks!

**Comment by lukax77** [comment]
resolved in rev. 683fd06

**Comment by nmaguirre** [comment]
Well done! Please notice that comments should be double indented with respect to the routine's indentation.
