### ISSUE TITLE
missing comments for routine ACCOUN_DIGIT.make_from_string_rep

### ISSUE THREAD

**Issue by ibongiovanni** [nmaguirre/eiffel-bank-ocr#7]
Routine 'make_from_string_rep' has no comments implemented

**Comment by ibongiovanni** [comment]
Solved in rev ecd4838

**Comment by nmaguirre** [comment]
This comment does not follow Eiffel's convention. Description of the routine goes immediately after the routine's name and signature:

routine (params)
-- Class creator...

Please correct this issue. Thanks!

**Comment by ibongiovanni** [comment]
Resolved in rev 01579a4

**Comment by nmaguirre** [comment]
Well done! Please notice that comments should be double indented with respect to the routine's indentation.
