### ISSUE TITLE
Missing Implementation for Routine ACCOUNT.DIGIT.set_value_from_string_rep

### ISSUE THREAD

**Issue by guttlein** [nmaguirre/eiffel-bank-ocr#8]
Implementation for Method ACCOUNT.DIGIT.set_value_from_string_rep is missing.

**Comment by dromero19** [comment]
Sorry, but the implementation of this routine is incorrect. You have to set 'value' somehow with the given parameter 'new_value'. You don't need the local variables declared. If you want I resolve this issue. Correct me if I'm wrong.

**Comment by dromero19** [comment]
Minor changes in the routine. Solved in rev. f82c457
