### ISSUE TITLE
missing implementation for routine out from class ACCOUNT_DIGIT

### ISSUE THREAD

**Issue by nicoboccolini** [nmaguirre/eiffel-bank-ocr#9]
Routine out from class ACCOUNT_DIGIT is not implemented. Implement this routine following the conventions, syntactic and methodological rules of Eiffel.

**Comment by nicoboccolini** [comment]
Solved in rev 6d627b271cd60c666dd8f0d62dcfa2db318d3a08

**Comment by nmaguirre** [comment]
Seems to be alright. Let's close it for the moment, and see what happens when we have tests for it. Well done!
